[[headers]]
  for = "/*"
  [headers.values]
    X-Establishment = "H"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    buildDir = "_site"
    exclude = [
      '**/event/**/*',
      '**/event/**/*.html'
    ]

[[plugins]]
  package = "netlify-plugin-html-validate"
  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"