[[headers]]
  for = "/*"
  [headers.values]
    X-Establishment = "H"
    Permissions-Policy = "interest-cohort=()"
    x-frame-options = "DENY"
    x-xss-protection = "1; mode=block"
    function = "strip-non-html-headers"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    buildDir = "_site"
    exclude = [
      '**/event/**/*',
      '**/event/**/*.html'
    ]

[[plugins]]
  package = "netlify-plugin-html-validate"
  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"