[[headers]]
  for = "/*"
  [headers.values]
    X-Establishment = "H"
    Permissions-Policy = "interest-cohort=()"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    function = "strip-non-html-headers"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.settings]
    locale = "en"
  [[plugins.inputs.audits]]
    # Only audit production site:
    url = "https://kudos.bike"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    buildDir = "_site"
    exclude = [
      '**/event/**/*',
      '**/event/**/*.html'
    ]

[[plugins]]
  package = "netlify-plugin-html-validate"
  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"
